select agree_id, GCIF_NO, CUST_NAME, CIF_NO, NOTE_NO, PRD_TP, 
PRD_NM,PRD_SEGMENT, ORG_LMT_AMT, CURR_LMT_AMT, BAL, ORIG_INT_RT, CURR_INT_RT, OTH_CURR_INT_RT,
CLCT_RTNG_FCL, ALLOW_PCT, ALLOW_PCT_ADD, RESTRUCT_CD, PASTDUE_SINCE_DT, PASTDUE_DAYS, WRITE_OFF_AMT,
WRITE_OFF_DT ,WRITE_OFF_YN  from pda.master_loan
where base_dt = {date}
and PRD_NM LIKE '%Credit Card%'
AND STATUS = '00001'