WITH 
ML AS (
SELECT DISTINCT 
BASE_DT, 
APPL_ID,
AGREE_ID,
GCIF_NO,
NOTE_NO,
ORG_LMT_AMT, 
CURR_LMT_AMT,
BAL CURR_OS, 
CURR_INT_RT,
CLCT_RTNG_FCL,
RESTRUCT_CD,
PASTDUE_SINCE_DT, 
PASTDUE_DAYS
FROM PDA.MASTER_LOAN
WHERE BASE_DT = '{dt}'
AND APPL_ID IN ('CP','XP')),

CECE AS (
SELECT DISTINCT GCIF_NO,
CARD_NMBR
FROM PDA.TBL_BAL_CC
WHERE BASE_DT = '{dt}'
AND (Block_Code is null
OR Block_code in(' ','C','H','P','Y','M','K','B')
OR (Block_code = 'U' and user_code2 not in ('RP','PZ','MX','KD','KE','BV','PB','PF','HT','PE','PO','PU','XU','XP','PW','SM'))
OR (Block_code in ('I','R','L','S','J','A','Q','W','N','O','G','F','D') and Curr_balance <> 0)
OR (Block_code='Z' and user_code2 not in ('RP','PZ','MX','KD','KE','BV','PB','PF','HT','PE','PO','PU','XU','XP','PW','SM') and curr_balance <> 0)
OR (block_code='E' and Curr_balance > 0)
OR (Block_Code = 'T' and Curr_balance = 0 and EXPIRE2 > '{ym}'))
),

JOINED AS(
SELECT
b.BASE_DT, 
b.APPL_ID,
b.AGREE_ID,
b.GCIF_NO, 
b.ORG_LMT_AMT, 
b.CURR_LMT_AMT, 
b.CURR_OS,
b.CURR_INT_RT, 
b.CLCT_RTNG_FCL,
b.RESTRUCT_CD, 
b.PASTDUE_SINCE_DT, 
b.PASTDUE_DAYS
FROM CECE a
INNER JOIN ML b
ON a.CARD_NMBR = b.NOTE_NO AND a.GCIF_NO = b.GCIF_NO
),

GPD AS(
SELECT
BASE_DT, 
APPL_ID,
GCIF_NO, 
COUNT(AGREE_ID) NOA, 
SUM(ORG_LMT_AMT)  ORG_LMT, 
SUM(CURR_LMT_AMT) CURR_LMT,
SUM(CURR_OS) CURR_OS,
SUM(CURR_INT_RT*CURR_OS) INT_AMT,
MAX(CLCT_RTNG_FCL) CP_CLCT, -- 00001-00005 for CP, 00001 for XP
SUM(CASE 
WHEN RESTRUCT_CD = '00001' THEN 1 -- 00001, 00005, 00008 for CP, null for XP
ELSE NULL
END) AS RESTRUCT_1,
SUM(CASE
WHEN RESTRUCT_CD = '00005' THEN 1
ELSE NULL
END) AS RESTRUCT_5,
SUM(CASE
WHEN RESTRUCT_CD = '00008' THEN 1
ELSE NULL
END) AS RESTRUCT_8,
MAX(CASE WHEN PASTDUE_SINCE_DT = '99991231' THEN 0
ELSE (TO_DATE(BASE_DT,'YYYYMMDD')-TO_DATE(PASTDUE_SINCE_DT,'YYYYMMDD'))
END) PASTDUE_DAYS_CALC,
MAX(CASE WHEN PASTDUE_SINCE_DT = '99991231' THEN '00000000'
ELSE PASTDUE_SINCE_DT
END) PASTDUE_DT_MAX,
MAX(PASTDUE_DAYS) PASTDUE_DAYS,
CASE WHEN MAX(PASTDUE_DAYS) = 0 THEN 'PERFORMING'
WHEN MAX(PASTDUE_DAYS) >= 1 AND MAX(PASTDUE_DAYS) < 30 THEN 'GRACE PERIOD'
WHEN MAX(PASTDUE_DAYS) >= 30 THEN 'DELINQUENT'
END AS CP_STATUS
FROM JOINED
GROUP BY
BASE_DT, 
APPL_ID,
GCIF_NO
)

SELECT
g.BASE_DT, 
g.APPL_ID,
g.GCIF_NO,
g.NOA,
g.ORG_LMT,
g.CURR_LMT,
g.CURR_OS,
g.INT_AMT,
g.CP_CLCT,
g.RESTRUCT_1,
g.RESTRUCT_5,
g.RESTRUCT_8,
g.PASTDUE_DAYS_CALC,
g.PASTDUE_DT_MAX,
g.PASTDUE_DAYS,
g.CP_STATUS
FROM 
GPD g