WITH 
ML AS (
SELECT DISTINCT 
BASE_DT, 
AGREE_ID,
GCIF_NO, 
CIF_NO, 
NOTE_NO, 
PRD_TP, 
PRD_NM,
PRD_SEGMENT, 
ORG_LMT_AMT, 
CURR_LMT_AMT, 
BAL OS, 
ORIG_INT_RT, 
CURR_INT_RT, 
OTH_CURR_INT_RT,
LAST_RNWL_DT,
ORIG_MAT_DT,
CURR_MAT_DT,
TENOR,
DAYS_REMAIN,
CLCT_RTNG_FCL, 
ALLOW_PCT, 
ALLOW_PCT_ADD, 
RESTRUCT_CD, 
PASTDUE_SINCE_DT, 
PASTDUE_DAYS, 
WRITE_OFF_AMT,
WRITE_OFF_DT, 
WRITE_OFF_YN,
CASE WHEN PASTDUE_DAYS = 0 THEN 'PERFORMING'
WHEN PASTDUE_DAYS >= 1 AND PASTDUE_DAYS < 30 THEN 'GRACE PERIOD'
WHEN PASTDUE_DAYS >= 30 THEN 'DELINQUENT'
END AS CC_STATUS
FROM PDA.MASTER_LOAN
WHERE BASE_DT = '{dt}'
AND PRD_NM LIKE '%Credit Card%'),

C360 AS (
SELECT DISTINCT 
GCIF_NO, 
SEGMENT, 
CUST_NM, 
OPEN_DATE, 
LAST_ACTIVE_DATE, 
CUST_TP, 
GENDER_CD, 
AGE,
CASE WHEN AGE>=50 THEN 'SAGA'
ELSE 'NON-SAGA'
END AS SAGA_FLAG,
EMPLOYMENT_TYPE,
CASE WHEN EMPLOYMENT_TYPE='EMPLOYED PERMANENT' THEN 'FIXED INCOME' 
ELSE 'NON-FIXED INCOME'
END AS INCOME_TYPE,
FUNDING_NOA, 
FUNDING_BAL,
FUNDING_AVG, 
NOA_DORMANT,
ALL_DORMANT,
CC,
PLOAN,
TR, 
PB, 
PRK, 
PPB, 
BG,
LC, 
KPR, 
KPM,
WOM,
COLLECT,
MF,
BONDS,
TRB,
M2U_USER,
CRTRX_MTD, 
CRTRX_AMT_MTD, 
DBTRX_MTD,
DBTRX_AMT_MTD
FROM PDA.CUSTOMER_360 WHERE BASE_DT = '{dt}'
),

CECE AS (
SELECT DISTINCT GCIF_NO,
CARD_NMBR
FROM PDA.TBL_BAL_CC
WHERE BASE_DT = '{dt}'
AND (Block_Code is null
OR Block_code in(' ','C','H','P','Y','M','K','B')
OR (Block_code = 'U' and user_code2 not in ('RP','PZ','MX','KD','KE','BV','PB','PF','HT','PE','PO','PU','XU','XP','PW','SM'))
OR (Block_code in ('I','R','L','S','J','A','Q','W','N','O','G','F','D') and Curr_balance <> 0)
OR (Block_code='Z' and user_code2 not in ('RP','PZ','MX','KD','KE','BV','PB','PF','HT','PE','PO','PU','XU','XP','PW','SM') and curr_balance <> 0)
OR (block_code='E' and Curr_balance > 0)
OR (Block_Code = 'T' and Curr_balance = 0 and EXPIRE2 > '{ym}'))
),

ML_BAL AS(
SELECT DISTINCT 
AGREE_ID,
MAX(BAL) MTD_MAX_OS,
AVG(BAL) MTD_AVG_OS
FROM PDA.MASTER_LOAN
WHERE BASE_DT LIKE '20'||'{ym}'||'%'
AND PRD_NM LIKE '%Credit Card%'
GROUP BY AGREE_ID
),

INST_BAL AS(
SELECT CARD_NO, SUM(ORG_CURR_AMT) INST_OS
FROM PDA.MASTER_CC_TRANSACTION
WHERE BASE_DT LIKE '{ym}'||'%'
GROUP BY CARD_NO
),

MARITAL_STS AS(
SELECT DISTINCT GCIF_NO, MARITAL_STS_CD 
FROM PDA.MASTER_DCIF_INDV
WHERE BASE_DT = '{dt}'
)

SELECT
b.BASE_DT, 
b.AGREE_ID,
b.GCIF_NO, 
b.CIF_NO, 
b.NOTE_NO, 
b.PRD_TP, 
b.PRD_NM,
b.PRD_SEGMENT, 
b.ORG_LMT_AMT, 
b.CURR_LMT_AMT, 
b.OS,
d.MTD_MAX_OS,
d.MTD_AVG_OS,
e.INST_OS,
b.ORIG_INT_RT, 
b.CURR_INT_RT, 
b.OTH_CURR_INT_RT,
b.LAST_RNWL_DT,
b.ORIG_MAT_DT,
b.CURR_MAT_DT,
b.TENOR,
b.DAYS_REMAIN,
b.CLCT_RTNG_FCL, 
b.ALLOW_PCT, 
b.ALLOW_PCT_ADD, 
b.RESTRUCT_CD, 
b.PASTDUE_SINCE_DT, 
b.PASTDUE_DAYS, 
b.WRITE_OFF_AMT,
b.WRITE_OFF_DT, 
b.WRITE_OFF_YN,
b.CC_STATUS,
c.SEGMENT, 
c.CUST_NM, 
c.OPEN_DATE, 
c.LAST_ACTIVE_DATE, 
c.CUST_TP, 
c.GENDER_CD, 
c.AGE,
c.SAGA_FLAG,
f.MARITAL_STS_CD
c.EMPLOYMENT_TYPE,
c.INCOME_TYPE,
c.FUNDING_NOA, 
c.FUNDING_BAL,
c.FUNDING_AVG, 
c.NOA_DORMANT,
c.ALL_DORMANT,
c.CC,
c.PLOAN,
c.TR, 
c.PB, 
c.PRK, 
c.PPB, 
c.BG,
c.LC, 
c.KPR, 
c.KPM,
c.WOM,
c.COLLECT,
c.MF,
c.BONDS,
c.TRB,
c.M2U_USER,
c.CRTRX_MTD, 
c.CRTRX_AMT_MTD, 
c.DBTRX_MTD,
c.DBTRX_AMT_MTD
FROM CECE a
INNER JOIN ML b
ON a.CARD_NMBR = b.NOTE_NO
INNER JOIN C360 c
ON a.GCIF_NO = c.GCIF_NO
LEFT JOIN ML_BAL d
ON b.AGREE_ID = d.AGREE_ID
LEFT JOIN INST_BAL e
ON b.NOTE_NO = e.CARD_NO
LEFT JOIN MARITAL_STS f
ON b.GCIF_NO = f.GCIF_NO